import itemFake from '../../../assets/img/random/cabin.png'

export const filtersMarketplace = [
  {
    id: 1,
    title: 'Novedades',
    itemCards: [
      {
        id: 11,
        img: itemFake,
        titleItem: 'Titulo 1',
        description: 'Description 1 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 1',
        price: 143000,
      },
      {
        id: 12,
        img: itemFake,
        titleItem: 'Titulo 2',
        description: 'Description 2 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 2',
        price: 143000,
      },
      {
        id: 13,
        img: itemFake,
        titleItem: 'Titulo 3',
        description: 'Description 3 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 3',
        price: 143000,
      },
      {
        id: 14,
        img: itemFake,
        titleItem: 'Titulo 4',
        description: 'Description 4 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 4',
        price: 143000,
      },
      {
        id: 15,
        img: itemFake,
        titleItem: 'Titulo 5',
        description: 'Description 1 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 5',
        price: 143000,
      },
    ],
  },
  {
    id: 2,
    title: 'Ofertas',
    itemCards: [
      {
        id: 21,
        img: itemFake,
        titleItem: 'Titulo 1',
        description: 'Description 1 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 1',
        price: 143000,
      },
      {
        id: 22,
        img: itemFake,
        titleItem: 'Titulo 2',
        description: 'Description 2 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 2',
        price: 143000,
      },
      {
        id: 23,
        img: itemFake,
        titleItem: 'Titulo 3',
        description: 'Description 3 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 3',
        price: 143000,
      },
      {
        id: 24,
        img: itemFake,
        titleItem: 'Titulo 4',
        description: 'Description 4 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 4',
        price: 143000,
      },
      {
        id: 25,
        img: itemFake,
        titleItem: 'Titulo 5',
        description: 'Description 1 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 5',
        price: 143000,
      },
    ],
  },
  {
    id: 3,
    title: 'Realands',
    itemCards: [
      {
        id: 31,
        img: itemFake,
        titleItem: 'Titulo 1',
        description: 'Description 1 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 1',
        price: 143000,
      },
      {
        id: 32,
        img: itemFake,
        titleItem: 'Titulo 2',
        description: 'Description 2 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 2',
        price: 143000,
      },
      {
        id: 33,
        img: itemFake,
        titleItem: 'Titulo 3',
        description: 'Description 3 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 3',
        price: 143000,
      },
      {
        id: 34,
        img: itemFake,
        titleItem: 'Titulo 4',
        description: 'Description 4 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 4',
        price: 143000,
      },
      {
        id: 15,
        img: itemFake,
        titleItem: 'Titulo 5',
        description: 'Description 1 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 5',
        price: 143000,
      },
    ],
  },
  {
    id: 4,
    title: 'Patchas',
    itemCards: [
      {
        id: 41,
        img: itemFake,
        titleItem: 'Titulo 1',
        description: 'Description 1 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 1',
        price: 143000,
      },
      {
        id: 42,
        img: itemFake,
        titleItem: 'Titulo 2',
        description: 'Description 2 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 2',
        price: 143000,
      },
      {
        id: 43,
        img: itemFake,
        titleItem: 'Titulo 3',
        description: 'Description 3 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 3',
        price: 143000,
      },
      {
        id: 44,
        img: itemFake,
        titleItem: 'Titulo 4',
        description: 'Description 4 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 4',
        price: 143000,
      },
      {
        id: 45,
        img: itemFake,
        titleItem: 'Titulo 5',
        description: 'Description 1 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 5',
        price: 143000,
      },
    ],
  },
  {
    id: 5,
    title: 'NFTs',
    itemCards: [
      {
        id: 51,
        img: itemFake,
        titleItem: 'Titulo 1',
        description: 'Description 1 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 1',
        price: 143000,
      },
      {
        id: 52,
        img: itemFake,
        titleItem: 'Titulo 2',
        description: 'Description 2 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 2',
        price: 143000,
      },
      {
        id: 53,
        img: itemFake,
        titleItem: 'Titulo 3',
        description: 'Description 3 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 3',
        price: 143000,
      },
      {
        id: 54,
        img: itemFake,
        titleItem: 'Titulo 4',
        description: 'Description 4 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 4',
        price: 143000,
      },
      {
        id: 55,
        img: itemFake,
        titleItem: 'Titulo 5',
        description: 'Description 1 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 5',
        price: 143000,
      },
    ],
  },
  {
    id: 6,
    title: 'Otros',
    itemCards: [
      {
        id: 61,
        img: itemFake,
        titleItem: 'Titulo 1',
        description: 'Description 1 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 1',
        price: 143000,
      },
      {
        id: 62,
        img: itemFake,
        titleItem: 'Titulo 2',
        description: 'Description 2 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 2',
        price: 143000,
      },
      {
        id: 63,
        img: itemFake,
        titleItem: 'Titulo 3',
        description: 'Description 3 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 3',
        price: 143000,
      },
      {
        id: 64,
        img: itemFake,
        titleItem: 'Titulo 4',
        description: 'Description 4 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 4',
        price: 143000,
      },
      {
        id: 65,
        img: itemFake,
        titleItem: 'Titulo 5',
        description: 'Description 1 lorem ipsum abcdefghijklmnñopqrstuvwxyz',
        author: 'Creador 5',
        price: 143000,
      },
    ],
  },
]
